# Generated by Django 5.0.14 on 2025-12-09 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_think_thought'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_thoughts', to=settings.AUTH_USER_MODEL),
        ),
    ]
